### ISSUE TITLE
Dispatcher TOML configuration file wrong for IPv6

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab#469]
At the Coordinator we now generate the `dispatcher.toml` file also for systemd, to be able to write the section `dispatcher.service_addresses`, e.g. in FITI1:
```toml
[dispatcher]
id = "dispatcher"
local_udp_forwarding = true

[metrics]
prometheus = "127.0.0.1:30441"

[dispatcher.service_addresses]
"27-ffaa:0:2101,CS" = "240a:a097:100:1::11:30254"
"27-ffaa:0:2101,DS" = "240a:a097:100:1::11:30254"

[log.console]
level = "info"
```

Note that it should say `"27-ffaa:0:2101,DS" = "[240a:a097:100:1::11]:30254"` instead of `"27-ffaa:0:2101,DS" = "240a:a097:100:1::11:30254"`, as IPv6 addresses are wrapped in `[]`.
